---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(Seurat)

data_path<-"/home/fgao/Data_single_cell/Stathopoulos_Lab/SE8011/"
dm.data<-Read10X_h5(paste(data_path, "cellranger_out/cellranger7_S1_dm6_transgene_out/outs/filtered_feature_bc_matrix.h5", sep=""), 
                    use.names = TRUE, unique.features = TRUE)

```


```{r}

dm<-CreateSeuratObject(dm.data, project = "cellranger")
plot <- FeatureScatter(dm, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot
dm[["percent.rRNA"]] <- PercentageFeatureSet(dm, pattern = "rRNA")
VlnPlot(dm, features = c("nFeature_RNA", "nCount_RNA", "percent.rRNA"), ncol = 3, pt.size = 0)


dm <- subset(dm, subset = nFeature_RNA < 7000 & nCount_RNA > 250 & nCount_RNA < 100000 & percent.rRNA<0.1)

```


#doublet detection and removal
```{r}

dm <- NormalizeData(dm, normalization.method = "LogNormalize", scale.factor = 10000)
dm <- FindVariableFeatures(dm, selection.method = "vst", nfeatures = 2000)

dm <- ScaleData(dm, verbose = FALSE, vars.to.regress = c("nCount_RNA"))
dm <- RunPCA(dm, npcs = 60, ndims.print = 1:5, nfeatures.print = 5)
ElbowPlot(dm, ndims = 60, reduction = "pca")

# t-SNE and Clustering

dm <- FindNeighbors(dm, reduction = "pca", dims = 1:30)

dm <- RunTSNE(dm, dims = 1:30, check_duplicates = FALSE)
dm <- RunUMAP(dm, dims = 1:30, check_duplicates = FALSE)

library(DoubletFinder)

nExp_dm <- round(ncol(dm) * 0.07)  # expect 7% doublets


options(future.globals.maxSize= 1600*1024^2)

dm <- doubletFinder_v3(dm, pN = 0.2, pK = 0.005, nExp = nExp_dm, PCs = 1:30, sct = TRUE)

DF.name_dm = colnames(dm@meta.data)[grepl("DF.classification", colnames(dm@meta.data))]

cowplot::plot_grid(ncol = 2, DimPlot(dm, group.by = "orig.ident") + NoAxes(), 
    DimPlot(dm, group.by = DF.name_dm) + NoAxes())

VlnPlot(dm, features = "nFeature_RNA", group.by = DF.name_dm, pt.size = 0)

dm = dm[, dm@meta.data[, DF.name_dm] == "Singlet"]
```


#low resolution clustering
```{r}

data_path<-"/home/fgao/Data_single_cell/Stathopoulos_Lab/SE8011/"
mtx_dm<-dm$RNA@counts

dm <- CreateSeuratObject(mtx_dm, project = "wt")
dm <- NormalizeData(dm, normalization.method = "LogNormalize", scale.factor = 10000)
#dm <- FindVariableFeatures(dm, selection.method = "vst", nfeatures = 2000)
dm <- FindVariableFeatures(dm, selection.method = "vst")
dm <- ScaleData(dm, verbose = FALSE, vars.to.regress = c("nCount_RNA"))
dm <- RunPCA(dm, npcs = 60, ndims.print = 1:5, nfeatures.print = 5)
ElbowPlot(dm)

dm <- FindNeighbors(dm, reduction = "pca", dims = 1:20)
dm <- RunTSNE(dm, dims = 1:20, check_duplicates = FALSE)
dm <- RunUMAP(dm, dims = 1:20, check_duplicates = FALSE)

dm <- FindClusters(dm, resolution = 0.2)
umap_cluster<-DimPlot(dm, reduction = "umap", group="seurat_clusters", label = TRUE)
tsne_cluster<-DimPlot(dm, reduction = "tsne", group="seurat_clusters", label = TRUE)

umap_cluster
tsne_cluster

data_id<-floor(runif(1, min=10000000, max=99999999))

saveRDS(dm,file=paste(data_path, data_id, "_220901Sta.rds", sep=""),compress=F)

```


#cell cycle analysis
```{r}

#s.genes <- cc.genes$s.genes
#g2m.genes <- cc.genes$g2m.genes
#data_all <- CellCycleScoring(data_all, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
#head(data_all[[]])

```


#pseudotime analysis

```{r}
library(monocle)

data_path<-"/home/fgao/Data_single_cell/Stathopoulos_Lab/SE8011/"
dm<-readRDS(paste(data_path, "76476877_220901Sta.rds", sep=""))
data_monocle <- as(as.matrix(dm$RNA@counts), 'sparseMatrix')

sample_sheet <- data.frame(barcode=colnames(dm), cluster=dm$seurat_clusters)
rownames(sample_sheet) <- sample_sheet$barcode

pd <- new("AnnotatedDataFrame", data = sample_sheet)
fData <- data.frame(gene_short_name = row.names(data_monocle), row.names = row.names(data_monocle))
fd <- new('AnnotatedDataFrame', data = fData)

#Construct monocle cds
monocle_cds <- newCellDataSet(data_monocle,
                         phenoData = pd,
                         featureData = fd,
                         lowerDetectionLimit = 0.5,
                         expressionFamily = negbinomial.size())

monocle_cds <- estimateSizeFactors(monocle_cds)

monocle_cds <- detectGenes(monocle_cds, min_expr = 0.1)

clustering_DEG_genes <- differentialGeneTest(monocle_cds, fullModelFormulaStr = '~cluster', cores = 4, relative_expr=FALSE)

ordering_genes <- row.names(clustering_DEG_genes)[order(clustering_DEG_genes$qval)][1:2000]
monocle_cds <- setOrderingFilter(monocle_cds, ordering_genes = ordering_genes)
monocle_cds <- reduceDimension(monocle_cds, method = 'DDRTree')
#monocle_cds <- orderCells(monocle_cds)

monocle_cds <- orderCells(monocle_cds, root_state = 9)
plot_pseudotime1<-plot_cell_trajectory(monocle_cds, color_by = 'as.factor(cluster)', cell_size=1)
plot_pseudotime1

plot_pseudotime2<-plot_cell_trajectory(monocle_cds, color_by = 'State', cell_size=1)
plot_pseudotime2

plot_pseudotime3<-plot_cell_trajectory(monocle_cds, color_by = 'Pseudotime', cell_size=1)
plot_pseudotime3

```


#Pseudotime DEG analysis
```{r}

#diff_test_res <- differentialGeneTest(monocle_cds, fullModelFormulaStr = "~sm.ns(Pseudotime)", cores = 4, relative_expr=FALSE)
#sig_gene_names <- row.names(subset(diff_test_res, qval < 0.05 & use_for_ordering==TRUE))
#plot_pseudotime_heatmap(monocle_cds[sig_gene_names,], num_clusters = 3, cores = 4, show_rownames = T)

to_be_tested1 <- row.names(subset(fData(monocle_cds),
gene_short_name %in% c("opa", "tin", "twi", "nos", "pgc", "gcl")))
cds_subset1 <- monocle_cds[to_be_tested1,]

to_be_tested2 <- row.names(subset(fData(monocle_cds),
gene_short_name %in% c("en", "hh", "wg", "slp1/2")))
cds_subset2 <- monocle_cds[to_be_tested2,]

plot_genes_in_pseudotime(cds_subset1, color_by = "Pseudotime", cell_size=0.1)
plot_genes_in_pseudotime(cds_subset2, color_by = "Pseudotime", cell_size=0.1)

```

#save trajectory images
```{r}

png(paste(data_path, "pseudotime_cluster.png", sep=""), width=640, height=480)
plot_pseudotime1
dev.off()

```



#high resolution clustering
```{r}

data_path<-"/home/fgao/Data_single_cell/Stathopoulos_Lab/SE8011/"
dm <- FindClusters(dm, resolution = 0.8)

umap_cluster<-DimPlot(dm, reduction = "umap", group="seurat_clusters", label = TRUE)
tsne_cluster<-DimPlot(dm, reduction = "tsne", group="seurat_clusters", label = TRUE)

umap_cluster
tsne_cluster

#VlnPlot(object = dm, features = c("mCD8-GFP"), ncol = 2, pt.size = 0)
#FeaturePlot(dm, features = c("mCD8-GFP"), min.cutoff = "q9", reduction="tsne")
#FeaturePlot(dm, features = c("mCD8-GFP"), min.cutoff = "q9", reduction="umap")
data_id<-floor(runif(1, min=10000000, max=99999999))

saveRDS(dm,file=paste(data_path, data_id, "_220909Sta.rds", sep=""),compress=F)


```


# Marker gene analysis

```{r}

library(dplyr)

markers <- FindAllMarkers(dm, only.pos = T)
write.table(markers, file=paste(data_path, file="markers_all_09012022.txt", sep=""), quote=F, sep="\t", col.names=T)

markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_logFC) -> top10


dm <- ScaleData(dm, features = rownames(dm))

library(ggplot2)
heatmap<-DoHeatmap(object = dm, features = top10$gene, size = 3, disp.min = -2, disp.max = 2, slot="scale.data") + scale_fill_gradientn(colors = c("blue", "white", "red"))
heatmap


svg(paste(data_path, "markers_heatmap_09012022.svg", sep=""), width=16, height=18)
heatmap
dev.off()

png(paste(data_path, "markers_heatmap_09012022.png", sep=""), width=1280, height=1280)
heatmap
dev.off()

```



